# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/sethsjo/Documents/myCode/ECS 153 - Hao Chen/Enigma-Machine-ECS153/src"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/sethsjo/Documents/myCode/ECS 153 - Hao Chen/Enigma-Machine-ECS153"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/sethsjo/Documents/myCode/ECS 153 - Hao Chen/Enigma-Machine-ECS153/CMakeFiles" "/Users/sethsjo/Documents/myCode/ECS 153 - Hao Chen/Enigma-Machine-ECS153//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/sethsjo/Documents/myCode/ECS 153 - Hao Chen/Enigma-Machine-ECS153/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Enigma

# Build rule for target.
Enigma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Enigma
.PHONY : Enigma

# fast build rule for target.
Enigma/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/build
.PHONY : Enigma/fast

#=============================================================================
# Target rules for targets named EnigmaTests

# Build rule for target.
EnigmaTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EnigmaTests
.PHONY : EnigmaTests

# fast build rule for target.
EnigmaTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/build
.PHONY : EnigmaTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

lib/Enigma.o: lib/Enigma.c.o
.PHONY : lib/Enigma.o

# target to build an object file
lib/Enigma.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Enigma.c.o
.PHONY : lib/Enigma.c.o

lib/Enigma.i: lib/Enigma.c.i
.PHONY : lib/Enigma.i

# target to preprocess a source file
lib/Enigma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Enigma.c.i
.PHONY : lib/Enigma.c.i

lib/Enigma.s: lib/Enigma.c.s
.PHONY : lib/Enigma.s

# target to generate assembly for a file
lib/Enigma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Enigma.c.s
.PHONY : lib/Enigma.c.s

lib/Plugboard.o: lib/Plugboard.c.o
.PHONY : lib/Plugboard.o

# target to build an object file
lib/Plugboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Plugboard.c.o
.PHONY : lib/Plugboard.c.o

lib/Plugboard.i: lib/Plugboard.c.i
.PHONY : lib/Plugboard.i

# target to preprocess a source file
lib/Plugboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Plugboard.c.i
.PHONY : lib/Plugboard.c.i

lib/Plugboard.s: lib/Plugboard.c.s
.PHONY : lib/Plugboard.s

# target to generate assembly for a file
lib/Plugboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Plugboard.c.s
.PHONY : lib/Plugboard.c.s

lib/Reflector.o: lib/Reflector.c.o
.PHONY : lib/Reflector.o

# target to build an object file
lib/Reflector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Reflector.c.o
.PHONY : lib/Reflector.c.o

lib/Reflector.i: lib/Reflector.c.i
.PHONY : lib/Reflector.i

# target to preprocess a source file
lib/Reflector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Reflector.c.i
.PHONY : lib/Reflector.c.i

lib/Reflector.s: lib/Reflector.c.s
.PHONY : lib/Reflector.s

# target to generate assembly for a file
lib/Reflector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Reflector.c.s
.PHONY : lib/Reflector.c.s

lib/Rotor.o: lib/Rotor.c.o
.PHONY : lib/Rotor.o

# target to build an object file
lib/Rotor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Rotor.c.o
.PHONY : lib/Rotor.c.o

lib/Rotor.i: lib/Rotor.c.i
.PHONY : lib/Rotor.i

# target to preprocess a source file
lib/Rotor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Rotor.c.i
.PHONY : lib/Rotor.c.i

lib/Rotor.s: lib/Rotor.c.s
.PHONY : lib/Rotor.s

# target to generate assembly for a file
lib/Rotor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Enigma.dir/build.make CMakeFiles/Enigma.dir/lib/Rotor.c.s
.PHONY : lib/Rotor.c.s

tests/AutograderTests.o: tests/AutograderTests.cpp.o
.PHONY : tests/AutograderTests.o

# target to build an object file
tests/AutograderTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/AutograderTests.cpp.o
.PHONY : tests/AutograderTests.cpp.o

tests/AutograderTests.i: tests/AutograderTests.cpp.i
.PHONY : tests/AutograderTests.i

# target to preprocess a source file
tests/AutograderTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/AutograderTests.cpp.i
.PHONY : tests/AutograderTests.cpp.i

tests/AutograderTests.s: tests/AutograderTests.cpp.s
.PHONY : tests/AutograderTests.s

# target to generate assembly for a file
tests/AutograderTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/AutograderTests.cpp.s
.PHONY : tests/AutograderTests.cpp.s

tests/EnigmaTests.o: tests/EnigmaTests.cpp.o
.PHONY : tests/EnigmaTests.o

# target to build an object file
tests/EnigmaTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/EnigmaTests.cpp.o
.PHONY : tests/EnigmaTests.cpp.o

tests/EnigmaTests.i: tests/EnigmaTests.cpp.i
.PHONY : tests/EnigmaTests.i

# target to preprocess a source file
tests/EnigmaTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/EnigmaTests.cpp.i
.PHONY : tests/EnigmaTests.cpp.i

tests/EnigmaTests.s: tests/EnigmaTests.cpp.s
.PHONY : tests/EnigmaTests.s

# target to generate assembly for a file
tests/EnigmaTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/EnigmaTests.cpp.s
.PHONY : tests/EnigmaTests.cpp.s

tests/ExampleTests.o: tests/ExampleTests.cpp.o
.PHONY : tests/ExampleTests.o

# target to build an object file
tests/ExampleTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/ExampleTests.cpp.o
.PHONY : tests/ExampleTests.cpp.o

tests/ExampleTests.i: tests/ExampleTests.cpp.i
.PHONY : tests/ExampleTests.i

# target to preprocess a source file
tests/ExampleTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/ExampleTests.cpp.i
.PHONY : tests/ExampleTests.cpp.i

tests/ExampleTests.s: tests/ExampleTests.cpp.s
.PHONY : tests/ExampleTests.s

# target to generate assembly for a file
tests/ExampleTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/ExampleTests.cpp.s
.PHONY : tests/ExampleTests.cpp.s

tests/PlugboardTests.o: tests/PlugboardTests.cpp.o
.PHONY : tests/PlugboardTests.o

# target to build an object file
tests/PlugboardTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/PlugboardTests.cpp.o
.PHONY : tests/PlugboardTests.cpp.o

tests/PlugboardTests.i: tests/PlugboardTests.cpp.i
.PHONY : tests/PlugboardTests.i

# target to preprocess a source file
tests/PlugboardTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/PlugboardTests.cpp.i
.PHONY : tests/PlugboardTests.cpp.i

tests/PlugboardTests.s: tests/PlugboardTests.cpp.s
.PHONY : tests/PlugboardTests.s

# target to generate assembly for a file
tests/PlugboardTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/PlugboardTests.cpp.s
.PHONY : tests/PlugboardTests.cpp.s

tests/ReflectorTests.o: tests/ReflectorTests.cpp.o
.PHONY : tests/ReflectorTests.o

# target to build an object file
tests/ReflectorTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/ReflectorTests.cpp.o
.PHONY : tests/ReflectorTests.cpp.o

tests/ReflectorTests.i: tests/ReflectorTests.cpp.i
.PHONY : tests/ReflectorTests.i

# target to preprocess a source file
tests/ReflectorTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/ReflectorTests.cpp.i
.PHONY : tests/ReflectorTests.cpp.i

tests/ReflectorTests.s: tests/ReflectorTests.cpp.s
.PHONY : tests/ReflectorTests.s

# target to generate assembly for a file
tests/ReflectorTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/ReflectorTests.cpp.s
.PHONY : tests/ReflectorTests.cpp.s

tests/RotorTests.o: tests/RotorTests.cpp.o
.PHONY : tests/RotorTests.o

# target to build an object file
tests/RotorTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/RotorTests.cpp.o
.PHONY : tests/RotorTests.cpp.o

tests/RotorTests.i: tests/RotorTests.cpp.i
.PHONY : tests/RotorTests.i

# target to preprocess a source file
tests/RotorTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/RotorTests.cpp.i
.PHONY : tests/RotorTests.cpp.i

tests/RotorTests.s: tests/RotorTests.cpp.s
.PHONY : tests/RotorTests.s

# target to generate assembly for a file
tests/RotorTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EnigmaTests.dir/build.make CMakeFiles/EnigmaTests.dir/tests/RotorTests.cpp.s
.PHONY : tests/RotorTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Enigma"
	@echo "... EnigmaTests"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... lib/Enigma.o"
	@echo "... lib/Enigma.i"
	@echo "... lib/Enigma.s"
	@echo "... lib/Plugboard.o"
	@echo "... lib/Plugboard.i"
	@echo "... lib/Plugboard.s"
	@echo "... lib/Reflector.o"
	@echo "... lib/Reflector.i"
	@echo "... lib/Reflector.s"
	@echo "... lib/Rotor.o"
	@echo "... lib/Rotor.i"
	@echo "... lib/Rotor.s"
	@echo "... tests/AutograderTests.o"
	@echo "... tests/AutograderTests.i"
	@echo "... tests/AutograderTests.s"
	@echo "... tests/EnigmaTests.o"
	@echo "... tests/EnigmaTests.i"
	@echo "... tests/EnigmaTests.s"
	@echo "... tests/ExampleTests.o"
	@echo "... tests/ExampleTests.i"
	@echo "... tests/ExampleTests.s"
	@echo "... tests/PlugboardTests.o"
	@echo "... tests/PlugboardTests.i"
	@echo "... tests/PlugboardTests.s"
	@echo "... tests/ReflectorTests.o"
	@echo "... tests/ReflectorTests.i"
	@echo "... tests/ReflectorTests.s"
	@echo "... tests/RotorTests.o"
	@echo "... tests/RotorTests.i"
	@echo "... tests/RotorTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

