
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/sethsjo/Library/Python/3.8/lib/python/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Darwin - 21.4.0 - arm64
...
